### ISSUE TITLE
Doppelter upload

### ISSUE THREAD

**Issue by hheller** [bikeable-ch/bikeable-frontend#59]
Passiert leider häufig, vorallem bei verwendung als webapp, siehe https://bikeable.ch/entries/bQBbApwKHSsLzNxCY und https://bikeable.ch/entries/cQue9uPhpvtDN5FvD

**Comment by hheller** [comment]
<img width="404" alt="bildschirmfoto 2019-02-15 um 09 43 09" src="https://user-images.githubusercontent.com/8961090/52845329-23671100-3107-11e9-84f3-bb4c52348935.png">

**Comment by diluno** [comment]
endlich fixed!

**Comment by lucnat** [comment]
bisch sicher? Han grad dopplet uplaoded

**Comment by diluno** [comment]
uf staging? isch ersch uf master deployed

**Comment by lucnat** [comment]
okok ich glaubs
