### ISSUE TITLE
Spot listing show more when going back to

### ISSUE THREAD

**Issue by hheller** [bikeable-ch/bikeable-frontend#84]
Wenn ich Likes 👍 oder Dislikes 👎 zu den Spots setze, muss ich in der Auflistung immer wieder von vorne anfangen und dann MEHR SPOTS mehrfach anklicken. Kann man die Website nicht so einrichten, dass ich beim Zurückschalten nach einem Spot wieder an die vorherige Stelle komme und zum nächsten Spot gehen kann?

**Comment by hheller** [comment]
Usercomment: "Was auf der Tablet-App funktioniert, geht auf der Website nicht: Nach Anklicken eines Spots, der weiter unten in der Liste steht, kann nicht zum nächsten Spot gegangen werden, man kommt wieder an den Anfang der Liste und muss sich runterscrollen und dann auch noch Mehr Spots anzeigen anklicken."

**Comment by diluno** [comment]
Ok, sollte jetzt einigermassen funktionieren mit dem Zurück-Button. Plz test!
