### ISSUE TITLE
Ungültiger Google Maps Api-Key für Staging

### ISSUE THREAD

**Issue by mgschwend** [bikeable-ch/bikeable-frontend#90]
Dadurch ist es leider nicht möglich auf Staging Spots zu erstellen...

**Comment by mgschwend** [comment]
Wollte eben ausprobieren, ob die Kategorien beim erstellen des Spots sauber gespeichert werden im Backend...

**Comment by diluno** [comment]
fixed

**Comment by mgschwend** [comment]
Nice, thx
